# Generated by Django 4.1.1 on 2022-11-17 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='contInStock',
            new_name='countInStock',
        ),
    ]
