# Generated by Django 4.1.3 on 2022-11-22 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_rename_continstock_product_countinstock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='contry',
            new_name='country',
        ),
    ]
