# Generated by Django 4.1.3 on 2022-12-20 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_order_rename_continstock_product_countinstock_and_more'),
        ('mainApp', '0008_review_createdat'),
    ]

    operations = [
    ]
