# Generated by Django 4.1.3 on 2022-12-20 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_product_image'),
        ('mainApp', '0009_merge_20221220_0911'),
    ]

    operations = [
    ]
